// <auto-generated />
namespace DataBase._MakarovaSpamMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCookies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCookies));
        
        string IMigrationMetadata.Id
        {
            get { return "201611272119296_AddCookies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
