// <auto-generated />
namespace DataBase._NovikovaSpamMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAsapField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAsapField));
        
        string IMigrationMetadata.Id
        {
            get { return "201610141854403_AddAsapField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
