// <auto-generated />
namespace DataBase.LajkiMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddHasCommentFiels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHasCommentFiels));
        
        string IMigrationMetadata.Id
        {
            get { return "201609071708046_AddHasCommentFiels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
