// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DataBase.GreenDozorMigrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFunctionaliReports : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFunctionaliReports));
        
        string IMigrationMetadata.Id
        {
            get { return "201610262134244_AddFunctionaliReports"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
