// <auto-generated />
namespace DataBase.LikeApplicationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddProxySpeedField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProxySpeedField));
        
        string IMigrationMetadata.Id
        {
            get { return "201610151607056_AddProxySpeedField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
