// <auto-generated />
namespace DataBase.SecondPageMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFriendsSearchField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFriendsSearchField));
        
        string IMigrationMetadata.Id
        {
            get { return "201608131537376_AddFriendsSearchField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
