// <auto-generated />
namespace DataBase.MirelleMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddInstagramId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInstagramId));
        
        string IMigrationMetadata.Id
        {
            get { return "201611261934557_AddInstagramId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
